/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed3;
  GtkWidget *cellview1;
  GtkWidget *SEARCH_ID;
  GtkWidget *entry26;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *entry29;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkWidget *entry30;
  GtkWidget *curve2;
  GtkWidget *entry46;
  GtkWidget *label57;
  GtkWidget *label59;
  GtkWidget *label146;
  GtkWidget *entry65;
  GtkWidget *button11;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label67;
  GtkWidget *label180;
  GtkWidget *entry_search;
  GtkWidget *search_add;
  GtkWidget *image34;
  GtkWidget *label56;
  GtkWidget *label55;
  GtkWidget *radiobuttonR1;
  GSList *radiobuttonR1_group = NULL;
  GtkWidget *radiobuttonR2;
  GtkWidget *label60;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *label90;
  GtkWidget *label145;
  GtkWidget *button10;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label66;
  GtkWidget *label53;
  GtkWidget *label49;
  GtkWidget *label52;
  GtkWidget *label144;
  GtkWidget *label51;
  GtkWidget *label50;
  GtkWidget *label179;
  GtkWidget *label54;
  GtkWidget *label58;
  GtkWidget *combobox5;
  GtkWidget *label_search_result;
  GtkWidget *button9;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image27;
  GtkWidget *label143;
  GtkWidget *FACEBOOK;
  GtkWidget *alignment37;
  GtkWidget *hbox37;
  GtkWidget *image40;
  GtkWidget *label209;
  GtkWidget *INSTAGRAM;
  GtkWidget *alignment36;
  GtkWidget *hbox36;
  GtkWidget *image39;
  GtkWidget *label208;
  GtkWidget *label45;
  GtkWidget *eventbox1;
  GtkWidget *fixed6;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *fixed11;
  GtkWidget *entryid_delete;
  GtkWidget *afficher;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image35;
  GtkWidget *label203;
  GtkWidget *treeview3;
  GtkWidget *label_supp;
  GtkWidget *checkbutton_delete;
  GtkWidget *refresh;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image36;
  GtkWidget *label204;
  GtkWidget *DELETE;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label117;
  GtkWidget *label47;
  GtkWidget *fixed_date;
  GtkWidget *entrydate;
  GtkWidget *label177;
  GtkWidget *treeview2;
  GtkWidget *labeldate;
  GtkWidget *button_SEARCH__DATE;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image37;
  GtkWidget *label206;
  GtkWidget *label_res;
  GtkWidget *label48;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window5), notebook1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow1);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed3);

  cellview1 = gtk_cell_view_new ();
  gtk_widget_show (cellview1);
  gtk_fixed_put (GTK_FIXED (fixed3), cellview1, 568, 656);
  gtk_widget_set_size_request (cellview1, 50, 50);

  SEARCH_ID = gtk_fixed_new ();
  gtk_widget_show (SEARCH_ID);
  gtk_fixed_put (GTK_FIXED (fixed3), SEARCH_ID, 0, 0);
  gtk_widget_set_size_request (SEARCH_ID, 728, 1104);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), entry26, 104, 88);
  gtk_widget_set_size_request (entry26, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), entry27, 104, 128);
  gtk_widget_set_size_request (entry27, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), entry28, 104, 160);
  gtk_widget_set_size_request (entry28, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), entry29, 104, 48);
  gtk_widget_set_size_request (entry29, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  spinbutton8_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), spinbutton8, 64, 304);
  gtk_widget_set_size_request (spinbutton8, 38, 24);

  spinbutton9_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), spinbutton9, 192, 304);
  gtk_widget_set_size_request (spinbutton9, 56, 24);

  spinbutton10_adj = gtk_adjustment_new (2000, 2000, 2025, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), spinbutton10, 312, 304);
  gtk_widget_set_size_request (spinbutton10, 88, 22);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), entry30, 104, 240);
  gtk_widget_set_size_request (entry30, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  curve2 = gtk_curve_new ();
  gtk_widget_show (curve2);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), curve2, 520, 608);
  gtk_widget_set_size_request (curve2, 16, 16);
  gtk_curve_set_range (GTK_CURVE (curve2), 0, 1, 0, 1);

  entry46 = gtk_entry_new ();
  gtk_widget_show (entry46);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), entry46, 88, 488);
  gtk_widget_set_size_request (entry46, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry46), _("+216"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry46), 8226);

  label57 = gtk_label_new (_("year"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label57, 256, 304);
  gtk_widget_set_size_request (label57, 54, 24);

  label59 = gtk_label_new (_("Gender"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label59, 24, 352);
  gtk_widget_set_size_request (label59, 49, 17);

  label146 = gtk_label_new (_("(a valid one please)"));
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label146, 264, 232);
  gtk_widget_set_size_request (label146, 136, 52);

  entry65 = gtk_entry_new ();
  gtk_widget_show (entry65);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), entry65, 104, 8);
  gtk_widget_set_size_request (entry65, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry65), 8226);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), button11, 48, 624);
  gtk_widget_set_size_request (button11, 120, 38);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button11), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Error"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox12), label67, FALSE, FALSE, 0);

  label180 = gtk_label_new ("");
  gtk_widget_show (label180);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label180, 264, 576);
  gtk_widget_set_size_request (label180, 267, 40);

  entry_search = gtk_entry_new ();
  gtk_widget_show (entry_search);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), entry_search, 448, 16);
  gtk_widget_set_size_request (entry_search, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry_search), _("       SEARCH BY ID"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_search), 8226);

  search_add = gtk_button_new ();
  gtk_widget_show (search_add);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), search_add, 616, 16);
  gtk_widget_set_size_request (search_add, 42, 29);

  image34 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_container_add (GTK_CONTAINER (search_add), image34);

  label56 = gtk_label_new (_("Month"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label56, 136, 304);
  gtk_widget_set_size_request (label56, 52, 20);

  label55 = gtk_label_new (_("day"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label55, 24, 304);
  gtk_widget_set_size_request (label55, 47, 22);

  radiobuttonR1 = gtk_radio_button_new_with_mnemonic (NULL, _("MAN"));
  gtk_widget_show (radiobuttonR1);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), radiobuttonR1, 40, 368);
  gtk_widget_set_size_request (radiobuttonR1, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonR1), radiobuttonR1_group);
  radiobuttonR1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonR1));

  radiobuttonR2 = gtk_radio_button_new_with_mnemonic (NULL, _("WOMEN"));
  gtk_widget_show (radiobuttonR2);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), radiobuttonR2, 144, 368);
  gtk_widget_set_size_request (radiobuttonR2, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonR2), radiobuttonR1_group);
  radiobuttonR1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonR2));

  label60 = gtk_label_new (_("Do you use ?"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label60, 0, 408);
  gtk_widget_set_size_request (label60, 152, 27);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("check"));
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), checkbutton5, 40, 440);
  gtk_widget_set_size_request (checkbutton5, 118, 24);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("espece"));
  gtk_widget_show (checkbutton6);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), checkbutton6, 152, 440);
  gtk_widget_set_size_request (checkbutton6, 118, 24);

  label90 = gtk_label_new (_("PHONE"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label90, 16, 488);
  gtk_widget_set_size_request (label90, 59, 22);

  label145 = gtk_label_new (_("(this field\n must contain 8 digits )"));
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label145, 256, 488);
  gtk_widget_set_size_request (label145, 162, 49);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), button10, 8, 544);
  gtk_widget_set_size_request (button10, 120, 37);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button10), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label66 = gtk_label_new_with_mnemonic (_("Edit"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox11), label66, FALSE, FALSE, 0);

  label53 = gtk_label_new (_("Governorate"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label53, 0, 208);
  gtk_widget_set_size_request (label53, 118, 17);

  label49 = gtk_label_new (_("Address"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label49, 16, 160);
  gtk_widget_set_size_request (label49, 87, 22);

  label52 = gtk_label_new (_("CIN"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label52, 32, 128);
  gtk_widget_set_size_request (label52, 50, 22);

  label144 = gtk_label_new (_("(this field \nmust contain 8 digits)"));
  gtk_widget_show (label144);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label144, 224, 128);
  gtk_widget_set_size_request (label144, 237, 35);

  label51 = gtk_label_new (_("first name"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label51, 24, 80);
  gtk_widget_set_size_request (label51, 74, 32);

  label50 = gtk_label_new (_("last name"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label50, 8, 48);
  gtk_widget_set_size_request (label50, 104, 26);
  gtk_misc_set_padding (GTK_MISC (label50), 0, 15);

  label179 = gtk_label_new (_("id"));
  gtk_widget_show (label179);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label179, 32, 16);
  gtk_widget_set_size_request (label179, 57, 17);

  label54 = gtk_label_new (_("Email"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label54, 40, 248);
  gtk_widget_set_size_request (label54, 41, 17);

  label58 = gtk_label_new (_("Date of birth"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label58, 0, 264);
  gtk_widget_set_size_request (label58, 145, 39);

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), combobox5, 104, 200);
  gtk_widget_set_size_request (combobox5, 197, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("ARIANA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("BEJA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("BIZERTE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("BENAROUS"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("TATOUINE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("TOZEUR"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("TUNIS"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("JENDOUBA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("ZAGHOUANE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("SILIANA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("SOUSSE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("SIDI BOUZID"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("SFAX"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("GABES"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("GBELI"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("GASSERINE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("GAFSA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("KAIRAOUN"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("KEF"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("MEDNIN"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("MONASTIR"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("MANOUBA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("MAHDIA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("NABEUL"));

  label_search_result = gtk_label_new ("");
  gtk_widget_show (label_search_result);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), label_search_result, 450, 56);
  gtk_widget_set_size_request (label_search_result, 249, 32);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), button9, 144, 544);
  gtk_widget_set_size_request (button9, 120, 37);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button9), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image27 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox26), image27, FALSE, FALSE, 0);

  label143 = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_show (label143);
  gtk_box_pack_start (GTK_BOX (hbox26), label143, FALSE, FALSE, 0);

  FACEBOOK = gtk_button_new ();
  gtk_widget_show (FACEBOOK);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), FACEBOOK, 432, 552);
  gtk_widget_set_size_request (FACEBOOK, 124, 37);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (FACEBOOK), alignment37);

  hbox37 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox37);

  image40 = create_pixmap (window5, "456.svg");
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox37), image40, FALSE, FALSE, 0);

  label209 = gtk_label_new_with_mnemonic (_("FACEBOOK"));
  gtk_widget_show (label209);
  gtk_box_pack_start (GTK_BOX (hbox37), label209, FALSE, FALSE, 0);

  INSTAGRAM = gtk_button_new ();
  gtk_widget_show (INSTAGRAM);
  gtk_fixed_put (GTK_FIXED (SEARCH_ID), INSTAGRAM, 289, 552);
  gtk_widget_set_size_request (INSTAGRAM, 139, 37);

  alignment36 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (INSTAGRAM), alignment36);

  hbox36 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox36);
  gtk_container_add (GTK_CONTAINER (alignment36), hbox36);

  image39 = create_pixmap (window5, "123.png");
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox36), image39, FALSE, FALSE, 0);

  label208 = gtk_label_new_with_mnemonic (_("INSTAGRAM"));
  gtk_widget_show (label208);
  gtk_box_pack_start (GTK_BOX (hbox36), label208, FALSE, FALSE, 0);

  label45 = gtk_label_new (_("add and edit agent"));
  gtk_widget_show (label45);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label45);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), eventbox1);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (eventbox1), fixed6);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_fixed_put (GTK_FIXED (fixed6), toolbar1, 112, 488);
  gtk_widget_set_size_request (toolbar1, 29, 29);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH_HORIZ);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_fixed_put (GTK_FIXED (fixed6), fixed11, 80, 640);
  gtk_widget_set_size_request (fixed11, 0, 0);

  entryid_delete = gtk_entry_new ();
  gtk_widget_show (entryid_delete);
  gtk_fixed_put (GTK_FIXED (fixed6), entryid_delete, 96, 40);
  gtk_widget_set_size_request (entryid_delete, 219, 46);
  gtk_entry_set_text (GTK_ENTRY (entryid_delete), _("ENTER YOUR ID"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid_delete), 8226);

  afficher = gtk_toggle_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed6), afficher, 360, 40);
  gtk_widget_set_size_request (afficher, 150, 48);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (afficher), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image35 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox32), image35, FALSE, FALSE, 0);

  label203 = gtk_label_new_with_mnemonic (_("SHOW"));
  gtk_widget_show (label203);
  gtk_box_pack_start (GTK_BOX (hbox32), label203, FALSE, FALSE, 0);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview3, 128, 144);
  gtk_widget_set_size_request (treeview3, 300, 200);

  label_supp = gtk_label_new ("");
  gtk_widget_show (label_supp);
  gtk_fixed_put (GTK_FIXED (fixed6), label_supp, 368, 552);
  gtk_widget_set_size_request (label_supp, 182, 35);

  checkbutton_delete = gtk_check_button_new_with_mnemonic (_("ARE YOU SURE YOU WANT TO DELETE IT?"));
  gtk_widget_show (checkbutton_delete);
  gtk_fixed_put (GTK_FIXED (fixed6), checkbutton_delete, 376, 520);
  gtk_widget_set_size_request (checkbutton_delete, 308, 24);

  refresh = gtk_button_new ();
  gtk_widget_show (refresh);
  gtk_fixed_put (GTK_FIXED (fixed6), refresh, 224, 512);
  gtk_widget_set_size_request (refresh, 128, 48);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (refresh), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image36 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox33), image36, FALSE, FALSE, 0);

  label204 = gtk_label_new_with_mnemonic (_("REFRESH"));
  gtk_widget_show (label204);
  gtk_box_pack_start (GTK_BOX (hbox33), label204, FALSE, FALSE, 0);

  DELETE = gtk_toggle_button_new ();
  gtk_widget_show (DELETE);
  gtk_fixed_put (GTK_FIXED (fixed6), DELETE, 40, 512);
  gtk_widget_set_size_request (DELETE, 128, 48);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (DELETE), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label117 = gtk_label_new_with_mnemonic (_("DELETE"));
  gtk_widget_show (label117);
  gtk_box_pack_start (GTK_BOX (hbox22), label117, FALSE, FALSE, 0);

  label47 = gtk_label_new (_("apply/edit/delete"));
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label47);

  fixed_date = gtk_fixed_new ();
  gtk_widget_show (fixed_date);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed_date);

  entrydate = gtk_entry_new ();
  gtk_widget_show (entrydate);
  gtk_fixed_put (GTK_FIXED (fixed_date), entrydate, 144, 48);
  gtk_widget_set_size_request (entrydate, 236, 33);
  gtk_entry_set_text (GTK_ENTRY (entrydate), _("     Search by DATE (dd/mm/yyyy)"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydate), 8226);

  label177 = gtk_label_new ("");
  gtk_widget_show (label177);
  gtk_fixed_put (GTK_FIXED (fixed_date), label177, 344, 120);
  gtk_widget_set_size_request (label177, 57, 17);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed_date), treeview2, 72, 128);
  gtk_widget_set_size_request (treeview2, 300, 200);

  labeldate = gtk_label_new ("");
  gtk_widget_show (labeldate);
  gtk_fixed_put (GTK_FIXED (fixed_date), labeldate, 240, 520);
  gtk_widget_set_size_request (labeldate, 227, 31);

  button_SEARCH__DATE = gtk_button_new ();
  gtk_widget_show (button_SEARCH__DATE);
  gtk_fixed_put (GTK_FIXED (fixed_date), button_SEARCH__DATE, 40, 48);
  gtk_widget_set_size_request (button_SEARCH__DATE, 85, 32);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (button_SEARCH__DATE), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image37 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox34), image37, FALSE, FALSE, 0);

  label206 = gtk_label_new_with_mnemonic (_("SEARCH"));
  gtk_widget_show (label206);
  gtk_box_pack_start (GTK_BOX (hbox34), label206, FALSE, FALSE, 0);

  label_res = gtk_label_new ("");
  gtk_widget_show (label_res);
  gtk_fixed_put (GTK_FIXED (fixed_date), label_res, 384, 48);
  gtk_widget_set_size_request (label_res, 232, 32);

  label48 = gtk_label_new (_("afficher la liste des reservations faites par un citoyen a une date donn\303\251e"));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label48);

  g_signal_connect ((gpointer) search_add, "clicked",
                    G_CALLBACK (on_SEARCH_ADD_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonR1, "toggled",
                    G_CALLBACK (on_radiobuttonR1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonR2, "toggled",
                    G_CALLBACK (on_radiobuttonR2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5, "toggled",
                    G_CALLBACK (on_checkbutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton6, "toggled",
                    G_CALLBACK (on_checkbutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) FACEBOOK, "clicked",
                    G_CALLBACK (on_FACEBOOK_clicked),
                    NULL);
  g_signal_connect ((gpointer) INSTAGRAM, "clicked",
                    G_CALLBACK (on_INSTAGRAM_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_hercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_delete, "toggled",
                    G_CALLBACK (on_checkbutton_delete_toggled),
                    NULL);
  g_signal_connect ((gpointer) refresh, "clicked",
                    G_CALLBACK (on_refresh_clicked),
                    NULL);
  g_signal_connect ((gpointer) DELETE, "clicked",
                    G_CALLBACK (on_DELETE_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_SEARCH__DATE, "clicked",
                    G_CALLBACK (on_button_SEARCH__DATE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window5, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window5, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window5, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window5, cellview1, "cellview1");
  GLADE_HOOKUP_OBJECT (window5, SEARCH_ID, "SEARCH_ID");
  GLADE_HOOKUP_OBJECT (window5, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (window5, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (window5, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (window5, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (window5, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (window5, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (window5, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (window5, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (window5, curve2, "curve2");
  GLADE_HOOKUP_OBJECT (window5, entry46, "entry46");
  GLADE_HOOKUP_OBJECT (window5, label57, "label57");
  GLADE_HOOKUP_OBJECT (window5, label59, "label59");
  GLADE_HOOKUP_OBJECT (window5, label146, "label146");
  GLADE_HOOKUP_OBJECT (window5, entry65, "entry65");
  GLADE_HOOKUP_OBJECT (window5, button11, "button11");
  GLADE_HOOKUP_OBJECT (window5, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window5, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window5, image12, "image12");
  GLADE_HOOKUP_OBJECT (window5, label67, "label67");
  GLADE_HOOKUP_OBJECT (window5, label180, "label180");
  GLADE_HOOKUP_OBJECT (window5, entry_search, "entry_search");
  GLADE_HOOKUP_OBJECT (window5, search_add, "search_add");
  GLADE_HOOKUP_OBJECT (window5, image34, "image34");
  GLADE_HOOKUP_OBJECT (window5, label56, "label56");
  GLADE_HOOKUP_OBJECT (window5, label55, "label55");
  GLADE_HOOKUP_OBJECT (window5, radiobuttonR1, "radiobuttonR1");
  GLADE_HOOKUP_OBJECT (window5, radiobuttonR2, "radiobuttonR2");
  GLADE_HOOKUP_OBJECT (window5, label60, "label60");
  GLADE_HOOKUP_OBJECT (window5, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (window5, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (window5, label90, "label90");
  GLADE_HOOKUP_OBJECT (window5, label145, "label145");
  GLADE_HOOKUP_OBJECT (window5, button10, "button10");
  GLADE_HOOKUP_OBJECT (window5, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window5, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window5, image11, "image11");
  GLADE_HOOKUP_OBJECT (window5, label66, "label66");
  GLADE_HOOKUP_OBJECT (window5, label53, "label53");
  GLADE_HOOKUP_OBJECT (window5, label49, "label49");
  GLADE_HOOKUP_OBJECT (window5, label52, "label52");
  GLADE_HOOKUP_OBJECT (window5, label144, "label144");
  GLADE_HOOKUP_OBJECT (window5, label51, "label51");
  GLADE_HOOKUP_OBJECT (window5, label50, "label50");
  GLADE_HOOKUP_OBJECT (window5, label179, "label179");
  GLADE_HOOKUP_OBJECT (window5, label54, "label54");
  GLADE_HOOKUP_OBJECT (window5, label58, "label58");
  GLADE_HOOKUP_OBJECT (window5, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (window5, label_search_result, "label_search_result");
  GLADE_HOOKUP_OBJECT (window5, button9, "button9");
  GLADE_HOOKUP_OBJECT (window5, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window5, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window5, image27, "image27");
  GLADE_HOOKUP_OBJECT (window5, label143, "label143");
  GLADE_HOOKUP_OBJECT (window5, FACEBOOK, "FACEBOOK");
  GLADE_HOOKUP_OBJECT (window5, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (window5, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (window5, image40, "image40");
  GLADE_HOOKUP_OBJECT (window5, label209, "label209");
  GLADE_HOOKUP_OBJECT (window5, INSTAGRAM, "INSTAGRAM");
  GLADE_HOOKUP_OBJECT (window5, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (window5, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (window5, image39, "image39");
  GLADE_HOOKUP_OBJECT (window5, label208, "label208");
  GLADE_HOOKUP_OBJECT (window5, label45, "label45");
  GLADE_HOOKUP_OBJECT (window5, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window5, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window5, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window5, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window5, entryid_delete, "entryid_delete");
  GLADE_HOOKUP_OBJECT (window5, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (window5, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (window5, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (window5, image35, "image35");
  GLADE_HOOKUP_OBJECT (window5, label203, "label203");
  GLADE_HOOKUP_OBJECT (window5, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window5, label_supp, "label_supp");
  GLADE_HOOKUP_OBJECT (window5, checkbutton_delete, "checkbutton_delete");
  GLADE_HOOKUP_OBJECT (window5, refresh, "refresh");
  GLADE_HOOKUP_OBJECT (window5, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (window5, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (window5, image36, "image36");
  GLADE_HOOKUP_OBJECT (window5, label204, "label204");
  GLADE_HOOKUP_OBJECT (window5, DELETE, "DELETE");
  GLADE_HOOKUP_OBJECT (window5, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window5, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window5, image22, "image22");
  GLADE_HOOKUP_OBJECT (window5, label117, "label117");
  GLADE_HOOKUP_OBJECT (window5, label47, "label47");
  GLADE_HOOKUP_OBJECT (window5, fixed_date, "fixed_date");
  GLADE_HOOKUP_OBJECT (window5, entrydate, "entrydate");
  GLADE_HOOKUP_OBJECT (window5, label177, "label177");
  GLADE_HOOKUP_OBJECT (window5, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window5, labeldate, "labeldate");
  GLADE_HOOKUP_OBJECT (window5, button_SEARCH__DATE, "button_SEARCH__DATE");
  GLADE_HOOKUP_OBJECT (window5, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (window5, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (window5, image37, "image37");
  GLADE_HOOKUP_OBJECT (window5, label206, "label206");
  GLADE_HOOKUP_OBJECT (window5, label_res, "label_res");
  GLADE_HOOKUP_OBJECT (window5, label48, "label48");

  return window5;
}

